### ISSUE TITLE
[Infrastructure] As a user, I can see an initialized project with AWS cloud service integrated

### ISSUE THREAD

**Issue by nvminhtue** [nvminhtue/tyson_devops_ic#1]
## Why

Initialize the project with basic AWS modules. The project should have staging and production environments with isolated configurations.

## Acceptance Criteria

- Integrated with AWS cloud service
- Separated environment variables

**Comment by liamstevens111** [comment]
Do you plan to have separate repo for the demo project that will use this infrastructure? (to demo environment variables and using database and Elastic cache). I take it you will also use Elixir?

**Comment by liamstevens111** [comment]
Do we need an `Issue` for the following "new" requirement to the IC:

```
User and bot accounts for accessing the cloud provider are automatically provisioned. To fine-tune user access, different groups with different roles must be created.
(Setting up the IAM groups, roles, bot & user accounts.)
```
