### ISSUE TITLE
[Chore] As a user, I can see the infrastructure document

### ISSUE THREAD

**Issue by nvminhtue** [nvminhtue/tyson_devops_ic#14]
## Why

The Infrastructure document helps others have a general and comprehensive knowledge of how our system structures and works.

## Acceptance Criteria

- The document should contain detailed system requirements
- The document should list the necessary configuration steps

**Comment by liamstevens111** [comment]
> The document should contain detailed system requirements
 
 Is this the infrastructure diagram? If so maybe this can be separated out to a different issue which can be a `chore` instead of `feature`, and be one of the first tasks, ie `label/milestone 1` not `4`.

You will probably do this first before any technical documentation and configuration

**Comment by bterone** [comment]
Yes, I agree, this should be the first thing that we should be doing before planning out how to setup the infra 😄
