### ISSUE TITLE
Do we have Issue for up the IAM groups, roles, bot & user accounts?

### ISSUE THREAD

**Issue by liamstevens111** [nvminhtue/tyson_devops_ic#15]
Do we need an Issue for the following relatively new requirement to the IC:

User and bot accounts for accessing the cloud provider are automatically provisioned. To fine-tune user access, different groups with different roles must be created.
(Setting up the IAM groups, roles, bot & user accounts.)

Also, should we move these issues into a Github Project

**Comment by nvminhtue** [comment]
Nice, added [here](https://github.com/nvminhtue/tyson_devops_ic/issues/16) @liamstevens111
Feel free to close this issue if you think the latest one is match our requirements
