### ISSUE TITLE
[Infrastructure] As a user, I can see the project is set up with CI by GitHub Actions

### ISSUE THREAD

**Issue by nvminhtue** [nvminhtue/tyson_devops_ic#2]
## Why

The project should integrate with GitHub Actions for code linting and wiki publishing. 

## Acceptance Criteria

- Publish two workflows
  - Code Linting (Using `terraform fmt`, `tfsec`)
  - Wiki

**Comment by bterone** [comment]
Minor comment, but it's `terraform fmt` 👍

**Comment by liamstevens111** [comment]
> Minor comment, but it's terraform fmt 

Should we use `--recursive`? From memory I know I used this.
