### ISSUE TITLE
[Infrastructure] As a user, I can access the Terraform cloud

### ISSUE THREAD

**Issue by nvminhtue** [nvminhtue/tyson_devops_ic#3]
## Why

Integrate the Terraform cloud to help visualize the checks, deployments, and set variables.

## Acceptance Criteria

- Terraform Cloud is set and goes live.
- Deployments and Plans can be managed by Terraform cloud
- 3 workspaces should be created:
  - `workspace-production`: triggers run from `main` branch and `core` folder
  - `workspace-staging`: triggers run from. `develop` branch and `core` folder
  - `workspace-shared`: trigger run from `develop` branch and `shared` folder

**Comment by liamstevens111** [comment]
This includes the different the `3` different `Terraform Cloud Workspaces` with VCS integration right? One for `shared`, `staging` and `production`? 

staging will trigger on develop branch (from base/core + module changes) - execute from base/core
production will trigger on main branch (from base/core + module changes) - execute from base/core
shared will trigger on `develop?` branch (manual apply?) - execute from shared

Or some similiar configuration

**Comment by nvminhtue** [comment]
Updated, thanks @liamstevens111
