### ISSUE TITLE
[Infrastructure] As a user, I can connect to AWS ECR to manage the application Docker images

### ISSUE THREAD

**Issue by nvminhtue** [nvminhtue/tyson_devops_ic#4]
## Why

Integrate the AWS ECR (Elastic Container Registry) to connect with our application to store deployment docker containers.

## Acceptance Criteria

- AWS ECR service should be up and ready to connect with our application
- The application's docker images should be able to push and pull from ECR via the GitHub action workflow

**Comment by bterone** [comment]
Wanted to clarify this requirement a bit more, 
Typically we deploy to staging when we merge to the develop branch, and deploy to production when we merge to the main branch. Should we also include that in the acceptance criteria here?

**Comment by bterone** [comment]
I also think we might need to setup a bot account before this to handle pushing images, so perhaps we could do the requirement for automatically provisioning accounts prior to this? What do you think? 

I think there might be some complexity with setting up the relevant IAM permissions there 💭

**Comment by nvminhtue** [comment]
> Typically we deploy to staging when we merge to the develop branch, and deploy to production when we merge to the main branch. Should we also include that in the acceptance criteria here?

@bterone I think, I worth a separate task, which will mount a live project (i.e., Elixir hello world app) and handle these criterias in the CD section, what do you think?
